[project]
name = "litelines"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "outlines-core==0.2.11",
    "graphviz",
    "pydantic",
]
