[project]
name = "litelines"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "graphviz==0.21",
    "outlines-core==0.1.14",
    "xxhash==3.5.0",
]
